language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ianbattin-github"
    token:
      secure: "69e5dede7efb7a951af48ba6c8a486b765b50a9b"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'